version: "3.9"
services:
  mongo:
    image: mongo:bionic
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
  aerospike:
    image: "aerospike:ce-5.6.0.5"
    ports:
        - "3000-3002:3000-3002"